(function () {
  "use strict";

  const BERNINI_TASKS = {
    bernini_t2v: {
      tag: "T2V",
      sourceImage: false,
      sourceVideo: false,
      referenceImage: false,
      referenceVideo: false,
      prompt: "A cat walking through a sunny garden, cinematic",
    },
    bernini_t2i: {
      tag: "T2I",
      sourceImage: false,
      sourceVideo: false,
      referenceImage: false,
      referenceVideo: false,
      prompt: "a portrait of a woman in a red dress, studio lighting",
    },
    bernini_i2v: {
      tag: "I2V",
      sourceImage: true,
      sourceVideo: false,
      referenceImage: false,
      referenceVideo: false,
      prompt: "Animate this image with gentle camera push-in",
    },
    bernini_i2i: {
      tag: "I2I",
      sourceImage: true,
      sourceVideo: false,
      referenceImage: false,
      referenceVideo: false,
      prompt: "change the shirt color to blue",
    },
    bernini_v2v: {
      tag: "V2V",
      sourceImage: false,
      sourceVideo: true,
      referenceImage: false,
      referenceVideo: false,
      prompt: "Restyle the video into a watercolor look",
    },
    bernini_mv2v: {
      tag: "MV2V",
      sourceImage: false,
      sourceVideo: true,
      referenceImage: false,
      referenceVideo: false,
      prompt: "change the lighting to warm golden hour",
    },
    bernini_vi2v: {
      tag: "VI2V",
      sourceImage: false,
      sourceVideo: true,
      referenceImage: true,
      referenceVideo: false,
      prompt: "propagate the edit consistently across the whole clip",
    },
    bernini_vrc2v: {
      tag: "VRC2V",
      sourceImage: false,
      sourceVideo: true,
      referenceImage: false,
      referenceVideo: false,
      prompt: "make the subject raise their right hand",
    },
    bernini_r2v: {
      tag: "R2V",
      sourceImage: false,
      sourceVideo: false,
      referenceImage: true,
      referenceVideo: false,
      prompt: "This subject dancing on a neon stage",
    },
    bernini_r2i: {
      tag: "R2I",
      sourceImage: false,
      sourceVideo: false,
      referenceImage: true,
      referenceVideo: false,
      prompt: "this subject standing in a snowy street",
    },
    bernini_rv2v: {
      tag: "RV2V",
      sourceImage: false,
      sourceVideo: true,
      referenceImage: true,
      referenceVideo: false,
      prompt: "Replace the girl in the video with a girl dressed in student attire",
    },
    bernini_ads2v: {
      tag: "ADS2V",
      sourceImage: false,
      sourceVideo: true,
      referenceImage: false,
      referenceVideo: true,
      prompt: "Insert the product naturally onto the table",
    },
  };

  const BERNINI_IMAGE_MODES = new Set(["bernini_t2i", "bernini_i2i", "bernini_r2i"]);
  const EDIT_BERNINI_MODES = Object.keys(BERNINI_TASKS).filter((mode) => !BERNINI_IMAGE_MODES.has(mode));
  const BERNINI_DEFAULT_NEGATIVE = "bad video";
  const INPAINT_WORKFLOW_MODE = "wan_vace_inpaint";
  const INPAINT_DEFAULT_PROMPT = "Place the reference object naturally inside the painted area, matching lighting, scale, perspective, and motion.";
  const INPAINT_DEFAULT_NEGATIVE = "bad video";
  const DIRECTOR_DEFAULT_GLOBAL_PROMPT = "A continuous cinematic video with coherent subject identity, consistent lighting, natural motion, and smooth visual continuity across the full timeline.";
  const DIRECTOR_TIMELINE_PIXELS_PER_SECOND = 96;

  function createInitialState(workspace = "camera") {
    return {
      config: null,
      activeBatch: null,
      pollTimer: null,
      batchPreviewWaits: {},
      motionPreviewWaits: {},
      motionPendingCounter: 0,
      historyTimer: null,
      historyRuns: [],
      clockTimer: null,
      exampleAnimation: null,
      exampleDiagram: "",
      hiddenRunKeys: new Set(),
      sourcePath: "",
      middlePath: "",
      endPath: "",
      motionRefPath: "",
      motionGuideVideoPath: "",
      motionGuideDuration: 4,
      motionBatch: null,
      motionSubtab: "text",
      motion3d: {
        initialized: false,
        playing: false,
        time: 0,
        duration: 3,
        timeline: [],
        animationFrame: 0,
        lastTick: 0,
        refPath: "",
        guideUrl: "",
        generating: false,
      },
      audioPath: "",
      referencePaths: [""],
      referenceNames: [""],
      referencePreviewUrls: [""],
      referenceMeta: [{ type: "character", subject: "person_a" }],
      ingredientsSheetPath: "",
      ingredientsSheetName: "",
      ingredientsSheetPreviewUrl: "",
      directorSegments: [],
      directorVideoAudioSegments: [],
      directorIcVideoSegments: [],
      directorAudioSegments: [],
      directorMode: "generate",
      directorRetakeVideo: null,
      directorRetakeStart: 0,
      directorRetakeLength: 1,
      directorRetakePrompt: "",
      directorRetakeStrength: 1,
      directorRetakeDrag: null,
      directorRetakeAutoStitch: true,
      directorRetakePendingStitch: null,
      directorRetakeStitches: {},
      directorRetakeCompletedStitches: {},
      editRetakeContext: null,
      directorAudioModalTarget: "dialogue",
      directorSelectedId: "",
      directorSelectionType: "image",
      directorGlobalPromptInitialized: false,
      directorDrag: null,
      workspace,
      cameraWorkflowId: "",
      directorWorkflowId: "",
      berniniWorkflowId: "bernini_t2v",
      berniniSourceVideoPath: "",
      berniniSourceVideoName: "",
      berniniReferenceVideoPath: "",
      berniniReferenceVideoName: "",
      berniniReferenceImagePath: "",
      berniniReferenceImageName: "",
      inpaintWorkflowId: INPAINT_WORKFLOW_MODE,
      inpaintSourceVideoPath: "",
      inpaintSourceVideoName: "",
      inpaintReferenceImagePath: "",
      inpaintReferenceImageName: "",
      inpaintMaskImagePath: "",
      inpaintMaskPainted: false,
      inpaintDrawing: false,
      inpaintLastPoint: null,
      castingLines: [],
      castingLibrary: [],
      castingEdit: null,
      castingPreview: null,
      videoClipper: {
        slot: "",
        path: "",
        name: "",
        duration: 0,
        playing: false,
        renderingFilmstrip: false,
      },
      videoPreviewRun: null,
      frameExtractRun: null,
    };
  }

  window.CameraLabWorkspace = {
    BERNINI_TASKS,
    BERNINI_IMAGE_MODES,
    EDIT_BERNINI_MODES,
    BERNINI_DEFAULT_NEGATIVE,
    INPAINT_WORKFLOW_MODE,
    INPAINT_DEFAULT_PROMPT,
    INPAINT_DEFAULT_NEGATIVE,
    DIRECTOR_DEFAULT_GLOBAL_PROMPT,
    DIRECTOR_TIMELINE_PIXELS_PER_SECOND,
    createInitialState,
    visibleBerniniModes: () => [...EDIT_BERNINI_MODES],
  };
})();
